import type { SupabaseClient } from "@supabase/supabase-js";

import { supabase as defaultClient } from "@/lib/supabase";
import type { Database } from "@/lib/database.types";

type Client = SupabaseClient<Database>;

export interface PushSubscriptionRow {
  id: string;
  user_id: string;
  endpoint: string;
  user_agent: string | null;
  created_at: string;
  last_success_at: string | null;
  failure_count: number;
}

/**
 * Insert or refresh keys on a PushSubscription owned by the caller.
 * Idempotent on endpoint — same browser re-subscribing replaces its
 * old row (new keys are generated by the browser on every subscribe).
 */
export async function upsertMyPushSubscription(
  input: {
    endpoint: string;
    p256dh: string;
    auth: string;
    userAgent: string | null;
  },
  client: Client = defaultClient,
): Promise<string> {
  const { data, error } = await client.rpc("upsert_my_push_subscription", {
    p_endpoint: input.endpoint,
    p_p256dh: input.p256dh,
    p_auth: input.auth,
    p_user_agent: input.userAgent ?? undefined,
  });
  if (error) throw new Error(error.message);
  return data as string;
}

/**
 * Remove the caller's subscription by endpoint. Used when the user
 * toggles push off, or when the app detects permission revocation
 * and needs to clean up the stale DB row.
 */
export async function deleteMyPushSubscription(
  endpoint: string,
  client: Client = defaultClient,
): Promise<void> {
  const { error } = await client.rpc("delete_my_push_subscription", {
    p_endpoint: endpoint,
  });
  if (error) throw new Error(error.message);
}

/** List the caller's subscriptions — for a future "manage devices" UI. */
export async function listMyPushSubscriptions(
  client: Client = defaultClient,
): Promise<PushSubscriptionRow[]> {
  const { data, error } = await client
    .from("push_subscriptions")
    .select(
      "id, user_id, endpoint, user_agent, created_at, last_success_at, failure_count",
    )
    .order("created_at", { ascending: false });
  if (error) throw new Error(error.message);
  return (data ?? []) as PushSubscriptionRow[];
}

/** Toggle the caller's notify_via_push column. */
export async function updateMyNotifyViaPush(
  userId: string,
  enabled: boolean,
  client: Client = defaultClient,
): Promise<void> {
  const { error } = await client
    .from("profiles")
    .update({ notify_via_push: enabled })
    .eq("id", userId);
  if (error) throw new Error(error.message);
}
